### ISSUE TITLE
Problem in the miui music app

### ISSUE THREAD

**Issue by CabroX** [deivids84/MA-XML-7.0-CATALAN#19]
With this lenguage, the miui music app shows a force close. I tried english, spanish and even portuguese and the app works.

I paste the log here:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.miui.player/com.miui.player.ui.MusicBrowserActivity}: com.alibaba.fastjson.JSONException: unclosed string : '
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2464)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2526)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4122)
    at android.app.ActivityThread.access$900(ActivityThread.java:169)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
    at android.os.Handler.dispatchMessage(Handler.java:111)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5549)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
Caused by: com.alibaba.fastjson.JSONException: unclosed string : '
    at com.alibaba.fastjson.parser.JSONScanner.scanString(JSONScanner.java:731)
    at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:345)
    at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1041)
    at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1019)
    at com.alibaba.fastjson.JSON.parse(JSON.java:89)
    at com.alibaba.fastjson.JSON.parse(JSON.java:80)
    at com.miui.player.hybrid.toolbox.JSON.parseMap(JSON.java:63)
    at com.miui.player.content.LanguageManager.fillTexts(LanguageManager.java:130)
    at com.miui.player.content.LanguageManager.prepare(LanguageManager.java:61)
    at com.miui.player.content.LanguageManager.getString(LanguageManager.java:35)
    at com.miui.player.content.FrameConfigData.getString(FrameConfigData.java:90)
    at com.miui.player.content.FrameConfigData.getPageTitle(FrameConfigData.java:55)
    at com.miui.player.component.MusicNavigatorFragment.initNavigator(MusicNavigatorFragment.java:235)
    at com.miui.player.component.MusicNavigatorFragment.onObtainView(MusicNavigatorFragment.java:113)
    at com.miui.player.component.MusicHybridFragment.onObtainView(MusicHybridFragment.java:26)
    at com.miui.player.component.MusicBaseFragment.onInflateView(MusicBaseFragment.java:153)
    at com.miui.player.component.MusicFrameFragment.onInflateView(MusicFrameFragment.java:51)
    at com.miui.internal.app.FragmentDelegate.onCreateView(SourceFile:137)
    at miui.app.Fragment.onCreateView(SourceFile:62)
    at android.app.Fragment.performCreateView(Fragment.java:2069)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:899)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1072)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1054)
    at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1897)
    at android.app.Activity.performCreateCommon(Activity.java:5970)
    at android.app.Activity.performCreate(Activity.java:5977)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
    ... 11 more

Maybe an unclosed string as the error shows? 

Gràcies pel teu treball! :)

**Comment by deivids84** [comment]
No hi puc fer res, jo només puc solucionar problemes de traducció

**Comment by CabroX** [comment]
Entenc.

Gràcies igualment!
